[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
path = "lib.rs"

[dev-dependencies]
anyhow = "1.0.93"
csv = "1.3.0"
expect-test = "1.5.0"
itertools = "0.13.0"
schemars = "0.8.21"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
